#!/usr/bin/env python

import sys
sys.path.insert(0, sys.path[0]+'/waf_tools')

def options(opt):
    opt.load('hexapod_dart')

def configure(conf): 
    conf.get_env()['BUILD_GRAPHIC'] = False

    conf.load('hexapod_dart')
    conf.check_hexapod_dart()

def build(bld):
    bld.recurse('src/')
    